// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProofedAndPolished.Migrations
{
    [DbContext(typeof(ProofedAndPolishedDbContext))]
    [Migration("20250519225818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProofedAndPolished.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AmazonLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("numeric");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("InvoicedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PostedToFacebook")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PostedToWebsite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("SubGenre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WPH")
                        .HasColumnType("numeric");

                    b.Property<int?>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseKey")
                        .IsUnique();

                    b.HasIndex("GenreId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Uid");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmazonLink = "http://amazon.com/book1",
                            Author = "Jane Smith",
                            Date = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirebaseKey = "bk-001",
                            GenreId = 1,
                            HourlyRate = 75.00m,
                            Hours = 20m,
                            Image = "http://example.com/image1.jpg",
                            InvoicedAmount = 1500.00m,
                            PenName = "J.S.",
                            Rate = 0.03m,
                            ServiceId = 1,
                            SubGenre = "Epic",
                            Title = "The Enchanted Forest",
                            Uid = "admin-123",
                            WPH = 2500.0m,
                            WordCount = 50000
                        },
                        new
                        {
                            Id = 2,
                            AmazonLink = "http://amazon.com/book2",
                            Author = "Tom Writer",
                            Date = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirebaseKey = "bk-002",
                            GenreId = 2,
                            HourlyRate = 60.00m,
                            Hours = 12m,
                            Image = "http://example.com/image2.jpg",
                            InvoicedAmount = 720.00m,
                            PenName = "T.W.",
                            PostedToFacebook = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostedToWebsite = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rate = 0.04m,
                            ServiceId = 2,
                            SubGenre = "Contemporary",
                            Title = "Love in Shadows",
                            Uid = "va-456",
                            WPH = 2500.0m,
                            WordCount = 30000
                        });
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique();

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Note = "Want to use this as a formatting reference",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Romance"
                        });
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Editing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Proofreading"
                        });
                });

            modelBuilder.Entity("ProofedAndPolished.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Name = "Admin User",
                            Role = "admin",
                            Uid = "admin-123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "va@example.com",
                            Name = "VA User",
                            Role = "va",
                            Uid = "va-456"
                        });
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Book", b =>
                {
                    b.HasOne("ProofedAndPolished.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProofedAndPolished.Models.Service", "Service")
                        .WithMany("Books")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProofedAndPolished.Models.User", null)
                        .WithMany("Books")
                        .HasForeignKey("Uid")
                        .HasPrincipalKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Favorite", b =>
                {
                    b.HasOne("ProofedAndPolished.Models.Book", "Book")
                        .WithMany("Favorites")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofedAndPolished.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Book", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ProofedAndPolished.Models.Service", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ProofedAndPolished.Models.User", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
